FROM confluentinc/cp-server:7.2.1

USER root

RUN yum install -y \
     libmnl \
     findutils \
     which

RUN wget http://vault.centos.org/8.1.1911/BaseOS/x86_64/os/Packages/iptables-libs-1.8.2-16.el8.x86_64.rpm
RUN rpm -i --nodeps --nosignature http://vault.centos.org/8.1.1911/BaseOS/x86_64/os/Packages/iptables-libs-1.8.2-16.el8.x86_64.rpm

RUN wget http://vault.centos.org/8.1.1911/BaseOS/x86_64/os/Packages/iproute-tc-4.18.0-15.el8.x86_64.rpm
RUN rpm -i --nodeps --nosignature http://vault.centos.org/8.1.1911/BaseOS/x86_64/os/Packages/iproute-tc-4.18.0-15.el8.x86_64.rpm

#RUN rpm -i --nodeps --nosignature https://vault.centos.org/centos/8/BaseOS/x86_64/os/Packages/iproute-tc-5.12.0-4.el8.x86_64.rpm

#RUN rpm -i --nodeps --nosignature http://vault.centos.org/8.1.1911/BaseOS/x86_64/os/Packages/iproute-tc-4.18.0-15.el8.x86_64.rpm
