#!/bin/bash

source ../utils/utils.sh

docker-compose down -v
docker-compose up -d


KAFKA_1_IP=$(container_to_ip kafka-1)
KAFKA_2_IP=$(container_to_ip kafka-2)
KAFKA_3_IP=$(container_to_ip kafka-3)
KAFKA_4_IP=$(container_to_ip kafka-4)
KAFKA_5_IP=$(container_to_ip kafka-5)
KAFKA_6_IP=$(container_to_ip kafka-6)

ZOO_1_IP=$(container_to_ip zookeeper-1)
ZOO_2_IP=$(container_to_ip zookeeper-2)
ZOO_3_IP=$(container_to_ip zookeeper-3)
interface=eth0


main() {
	sleep 60

	create_topic_mrc kafka-1 __consumer_offsets 50 '{"version": 2,"replicas": [{"count": 3, "constraints": {"rack": "wr"}}], "observers": [{"count": 3, "constraints": {"rack": "eo"}}] }'
	create_topic_mrc kafka-1 test 1 '{"version": 2,"replicas": [{"count": 3, "constraints": {"rack": "wr"}}], "observers": [{"count": 3, "constraints": {"rack": "eo"}}] }'

	sleep 20

	get_state zookeeper-1 test

	send_message_to_topic kafka-1 test 'before DC outage'
	read_messages kafka-1 1

	sleep 20
	zookeeper_mode zookeeper-1 zookeeper-2 zookeeper-3

	log 'Killing DC West'
        docker-compose kill kafka-1 kafka-2 kafka-3

	sleep 45

	get_state zookeeper-1 test
	get_state zookeeper-2 test
	get_state zookeeper-3 test
        
	describe_topic kafka-4 test
	zookeeper_mode zookeeper-1 zookeeper-2 zookeeper-3

        log 'Trying to produce to kafka-4'
	log "Time is now "+`date`+"\n"

	send_message_to_topic kafka-4 test "sending message during outage from kafka-4"


	log 'Now trying unclean leader election'
	docker-compose exec kafka-4 kafka-leader-election --all-topic-partitions --bootstrap-server localhost:9092 --election-type UNCLEAN

        sleep 10

	log 'Now send message after unclean leader election'
        	
	send_message_to_topic kafka-4 test "sending message during after unclean leader election from kafka-4"

	log 'Network outage ends'
	#remove_partition kafka-1 kafka-2 kafka-3 kafka-4 kafka-5 kafka-6 zookeeper-1 zookeeper-2 zookeeper-3
        docker-compose up -d 

	log 'Waiting for the system to recover'
	sleep 45


	get_state zookeeper-1 test
	get_state zookeeper-2 test
	get_state zookeeper-3 test

	send_message kafka-1 'after network outage'
	read_messages kafka-1 3

	log 'sleeping for 5 min to trigger preferred leader election'
        sleep 300
	log 'describe topic after'
        describe_topic kafka-4 test

}

main
